In [6]:
from scipy.optimize import minimize
import pandas as pd
import numpy as np

In [32]:
D = np.array([1, 1, 1, 1])
A = np.array([[1000, 258412],
            [0, 4],
            [25694, 35471],
            [10256, 878787]])
B = np.array([10000000000000000000000, 450002200001])

def f(w,d):
    return ((w/d-1)**2)

def objective(W):
    return (1/2)*sum(
        d_k*f(w_k, d_k) for w_k, d_k in zip(W, D)
    )

def constraint(W):
    return A@W-B

constraints = {"type" : "eq", "fun" : constraint}

result = minimize(objective, 
                  x0=D, 
                  method="SLSQP", 
                  constraints=constraints)

ValueError: 'x0' must only have one dimension.

In [30]:
result

  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: 0.0
        x: [ 1.000e+00  1.000e+00  1.000e+00  1.000e+00]
      nit: 0
      jac: [ 7.451e-09  7.451e-09  7.451e-09  7.451e-09]
 hess_inv: [[1 0 0 0]
            [0 1 0 0]
            [0 0 1 0]
            [0 0 0 1]]
     nfev: 5
     njev: 1

In [35]:
import numpy as np
from scipy.optimize import minimize

# Define known values
D = np.array([1, 1, 1, 1])  # 4 elements

# Adjusted A to match the shape (4x4) so that A@W is valid
A = np.array([[1000, 258412, 1, 0],
              [0, 4, 1, 2],
              [25694, 35471, 5, 6],
              [10256, 878787, 2, 3]])

B = np.array([10000000000000000000000, 450002200001, 12345, 67890])  # Should have 4 elements

# Objective function (least squares)
def f(w, d):
    return ((w/d - 1) ** 2)

def objective(W):
    return (1/2) * sum(d_k * f(w_k, d_k) for w_k, d_k in zip(W, D))

# Constraint function ensuring A@W = B
def constraint(W):
    return A @ W - B  # Must be zero for equality constraint

# Define constraint in scipy format
constraints = {"type": "eq", "fun": constraint}

# Initial guess (same size as D)
x0 = D.copy()

# Solve optimization with an appropriate solver (SLSQP supports constraints)
result = minimize(objective, x0=x0, method="BFGS", constraints=constraints)

# Output results
print("Optimal W:", result.x)
print("Minimum objective value:", result.fun)


Optimal W: [1. 1. 1. 1.]
Minimum objective value: 0.0


/tmp/ipykernel_1320/3417717691.py:33: RuntimeWarning: Method BFGS cannot handle constraints.
  result = minimize(objective, x0=x0, method="BFGS", constraints=constraints)


In [36]:
result

  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: 0.0
        x: [ 1.000e+00  1.000e+00  1.000e+00  1.000e+00]
      nit: 0
      jac: [ 7.451e-09  7.451e-09  7.451e-09  7.451e-09]
 hess_inv: [[1 0 0 0]
            [0 1 0 0]
            [0 0 1 0]
            [0 0 0 1]]
     nfev: 5
     njev: 1