In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import pandas as pd
import sys
sys.path.append("../src")
from margin_calibration import MarginCalibration

# Dataset Generation

In [11]:
W_i = np.array([1/100, 1/100, 1/100, 1/100])
A = np.array([[1000, 2584],
            [1, 4],
            [25, 354],
            [102, 878]])
B = np.array([100000, 450002])

# Margin Calibration

In [12]:
mc=MarginCalibration()
mc_logit=MarginCalibration("logit", .5, 1.5)
mc_rr=MarginCalibration("raking_ratio")
mc_lt=MarginCalibration("truncated_linear", .5, 1.5)

In [13]:
mc.calibration(W_i, A, B).x

array([ 71.89368821, 100.28820185, 163.94420725, 234.38645502])

In [14]:
mc_logit.calibration(W_i, A, B).x

array([ 72.34155868, 150.17133266, 185.01668692, 224.34475954])

In [15]:
mc_rr.calibration(W_i, A, B).x

array([ 71.62271099, 100.17630838, 152.1805638 , 239.92743734])

In [16]:
mc_lt.calibration(W_i, A, B).x

array([ 72.34155871, 150.17133519, 185.0166886 , 224.34475875])

# Penalized Margin Calibration

In [ ]:
mc=MarginCalibration()
mc_logit=MarginCalibration("logit", .5, 1.5)
mc_rr=MarginCalibration("raking_ratio")
mc_lt=MarginCalibration("truncated_linear", .5, 1.5)