In [104]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [105]:
import numpy as np
import pandas as pd
import warnings
import sys

sys.path.append("../src")
from margin_calibration import MarginCalibration

In [106]:
warnings.simplefilter("ignore")

# Dataset Generation

In [107]:
# Create a 100 random observations with their respective
# sampling weights, such that those weights sum to 20 %
n_obs = 100
sampling_probabilities = np.random.rand(n_obs, 1).flatten()
sampling_probabilities = sampling_probabilities / sampling_probabilities.sum() *.2

# Create a matrix of size n_obs * n_margins, with margins ranging from 0 to 1000
n_margins = 2 # Let say we have two variables
calibration_matrix = 1000*np.random.rand(n_obs, n_margins)

# Now we create the calibration target
# It is of sier n_margins * 1 and contains the 
# sums of the margins over all the population
calibration_target = np.array([np.sum(calibration_matrix[:, i])*100 for i in range(calibration_matrix.shape[1])])

# The costs should be of size of the number of margins
costs = (1,1) # We give here same costs to both variables

# Margin Calibration

In [111]:
mc=MarginCalibration()
mc_logit=MarginCalibration("logit", .5, 1.5)
mc_rr=MarginCalibration("raking_ratio")
mc_lt=MarginCalibration("truncated_linear", .5, 1.5)

In [112]:
%%time
mc.calibration(sampling_probabilities, calibration_matrix, calibration_target).x

CPU times: user 1.4 s, sys: 3.99 ms, total: 1.4 s
Wall time: 206 ms


array([ 6.41993384e+02, -6.26411876e+01,  6.29861122e+01,  9.04233130e+01,
        1.38880822e+02,  1.30876907e+02,  1.66642258e+02, -6.82007061e+01,
        6.72556071e+01,  9.02531876e+01, -2.93658653e+01,  2.47540207e+02,
       -2.29235151e+00,  1.23162780e+01,  4.70909172e+01,  1.94769341e+02,
        1.48597255e+02,  2.70992960e+03, -1.66489334e+01,  1.23109464e+02,
       -3.53442141e+01, -3.02547074e+02,  1.92399334e+02,  1.72954844e+02,
        9.84236657e+02,  6.72711492e+02,  2.89791050e+01, -9.08261903e+00,
        3.44584961e+02,  8.39170668e+00,  4.81061807e+02, -3.05862089e+02,
        4.76139920e+01, -3.66502695e+01,  3.05543549e+02,  1.76347570e+02,
        5.34485465e+02, -1.44834218e+00, -1.59841552e+02, -1.27166061e+02,
        6.46487338e+01, -3.55393195e+02,  6.99995218e+01, -1.04608590e+03,
       -3.68531293e+02,  8.05957120e+01,  5.08287478e+02, -2.07646677e+02,
        9.96291241e+00,  2.91250487e+02,  3.90439131e+01,  2.12951503e+02,
        1.47067283e+02,  

In [113]:
%%time
mc_logit.calibration(sampling_probabilities, calibration_matrix, calibration_target).x

CPU times: user 1h 56min 3s, sys: 3.64 s, total: 1h 56min 6s
Wall time: 3min 52s


array([  682.54946855,  -733.37695001,  -152.80896794,  -495.27711301,
          47.56328237,  -323.91692863,    52.66145658, -1285.92776754,
        -160.33727359,   213.62910182,  -536.28069437,  -236.48018788,
        -323.36554819,  -818.91189128,  -661.48149874,   256.31565643,
        -264.94134165, 18789.48441823,  -821.08312918,  -168.95061671,
       -1123.67524075,   626.57597723,   762.20439626,   155.80162486,
        1335.48114788,  1869.34350174,  -203.22363837, -1048.39582431,
         175.72540171,  -285.93856641,   412.32817853,  3535.19031689,
        -329.90609515,  -841.47432283,   -26.72785974,   -98.52874271,
        1354.75327251,  -824.85745865, -1154.24964735, -1288.22930918,
         -41.94934404,  -607.89079691,   349.4302462 ,  1042.9736612 ,
        5272.74445884,  -163.88831399,  1403.62622408, -1283.44601342,
         709.81978825,   498.10727035,  -514.81306692,   -40.2656144 ,
        -181.24478925,  1418.39853492, -1097.59377471,  -106.04287365,
      

In [114]:
%%time
mc_rr.calibration(sampling_probabilities, calibration_matrix, calibration_target).x

CPU times: user 31min 35s, sys: 1.1 s, total: 31min 36s
Wall time: 1min 3s


array([ 214.26287207,   24.27600319,   31.16406382,   29.48799086,
         60.18863029,   41.02290592,   71.35509641,    5.98789362,
         35.79043153,   52.31751776,   28.74658774,  100.54208239,
         37.78136139,   14.03177503,   17.94160365,   87.45108986,
         63.13443553, 1879.01584606,   10.4733563 ,   51.85373749,
          7.24571442,  130.02527344,  109.22215281,   89.38928005,
        468.37019151,  391.43113674,   24.14071308,   10.01975354,
        125.65705581,   20.5450812 ,  316.36661407,  316.37764822,
         23.58636319,    8.68944889,  169.6046775 ,   90.75888184,
        350.85527905,   11.78196675,   16.69091495,    7.16899152,
         31.07243426,   42.62687274,   78.42398323,   87.33804233,
        321.9892762 ,   40.36318402,  197.5471232 ,    6.16670039,
        117.21886478,  151.94919993,   23.6501358 ,   81.82294579,
         50.08612881,  874.75632674,    7.83197373,   43.10581016,
         17.31441782,    9.80998054,  288.87248322,   64.01307

In [115]:
%%time
mc_lt.calibration(sampling_probabilities, calibration_matrix, calibration_target).x

CPU times: user 1h 23min 9s, sys: 4.85 s, total: 1h 23min 14s
Wall time: 2min 46s


array([ 2.08586817e+01, -4.49273388e+02, -1.07029486e+02, -4.41258681e+02,
       -3.46187783e+02, -4.16877909e+02, -1.82821895e+02, -7.64176330e+02,
       -1.92534901e+02,  1.43628491e+02, -4.72274759e+02, -1.72668666e+02,
       -4.19313385e+02, -5.74741994e+02, -8.45597263e+02, -8.53046686e+00,
       -7.97038673e+01,  1.89133081e+04, -5.53061084e+02, -3.46991158e+01,
       -8.16960466e+02,  8.70442460e+02,  2.82660208e+02,  1.11261986e+02,
        1.33026964e+03,  1.23828076e+03, -1.72483484e+02, -7.79714471e+02,
       -1.21441689e+02, -1.78915786e+02,  4.53272684e+02,  3.95141901e+03,
       -2.52888669e+02, -4.91226771e+02,  8.16278972e+01,  5.96795822e+01,
        3.71176732e+02, -6.83327431e+02, -6.65956708e+02, -7.69682136e+02,
       -1.42226075e+02, -6.40629508e+02, -4.93288133e+02,  1.04903117e+03,
        5.51787356e+03, -2.16925474e+02,  7.27128037e+02, -6.36007391e+02,
        1.97839029e+02,  3.30279950e+02, -3.42079515e+02, -1.39158594e+02,
       -3.27028448e+02,  

# Penalized Margin Calibration

In [121]:
mc_pen=MarginCalibration(penalty=.1, costs=costs)
mc_logit_pen=MarginCalibration("logit", .5, 1.5, penalty=.1, costs=costs)
mc_rr_pen=MarginCalibration("raking_ratio", penalty=.1, costs=costs)
mc_lt_pen=MarginCalibration("truncated_linear", .5, 1.5, penalty=.1, costs=costs)

In [122]:
%%time
mc_pen.calibration(sampling_probabilities, calibration_matrix, calibration_target).x

CPU times: user 307 ms, sys: 9 μs, total: 307 ms
Wall time: 49.1 ms


array([ 5.87543776e+02, -1.00163486e+03, -6.32930566e+02, -1.26108208e+03,
       -6.74420743e+02, -1.19940071e+03, -4.03292516e+02, -1.73717090e+03,
       -6.52105125e+02,  5.66407536e-01, -1.02194069e+03, -7.05695812e+02,
       -7.59346215e+02, -1.43167441e+03, -2.01912665e+03, -1.23075896e+02,
       -5.97545637e+02,  3.59819947e+04, -1.37864056e+03, -5.12453783e+02,
       -1.77794985e+03,  1.87744917e+03,  2.49394869e+02, -1.40591142e+02,
        2.51494314e+03,  1.49247973e+03, -7.34119001e+02, -1.73953885e+03,
       -2.46108188e+02, -7.49270246e+02,  4.46582964e+02,  6.06486805e+03,
       -9.41546521e+02, -1.27667376e+03, -1.97998360e+02, -2.95457947e+02,
        3.39228210e+02, -1.61169653e+03, -1.37898749e+03, -1.97098780e+03,
       -7.00185250e+02, -3.67933217e+02, -1.74391029e+02,  2.11438136e+03,
        8.45116021e+03, -6.90324437e+02,  1.63560942e+03, -1.92208075e+03,
        9.04268956e+02,  5.66505388e+02, -1.05801451e+03, -6.09405016e+02,
       -1.03680213e+03,  

In [123]:
%%time
mc_logit_pen.calibration(sampling_probabilities, calibration_matrix, calibration_target).x

CPU times: user 3.06 s, sys: 4.13 ms, total: 3.06 s
Wall time: 446 ms


array([ 1018.7949904 ,   338.35844878,   160.00629474,   161.03319896,
         425.61288589,   157.80723684,   373.26137728,   138.83191405,
         212.14050834,   196.06288646,   364.15400587,   200.76478558,
         405.7576084 ,   143.69820745,   210.26928743,   301.3289038 ,
         138.0961964 , 18913.27169843,   133.93433378,   147.85114548,
         130.26115985,  1771.49009669,   192.82841705,   152.59743591,
        1557.05656896,   765.66594436,   170.76719754,   139.4089952 ,
         460.06359786,   168.63211718,   328.21985306,  3867.31039226,
         149.47366841,   128.59834853,   208.51135901,   139.14654431,
         341.42746523,   146.24614851,   375.20294763,   218.45425073,
         165.34277423,   955.79921606,   911.54138272,  2087.36495761,
        5471.60267102,   248.25999089,  1837.26315849,   252.680389  ,
        1220.57543907,   497.1922944 ,   184.06022057,   222.03612175,
         152.96698266,  1686.11143517,   142.93572669,   184.49883891,
      

In [124]:
%%time
mc_rr_pen.calibration(sampling_probabilities, calibration_matrix, calibration_target).x

CPU times: user 7.29 s, sys: 16.1 ms, total: 7.3 s
Wall time: 1.05 s


array([2.28438650e-06, 2.48595974e-06, 4.13176846e-06, 4.23430546e-06,
       1.49675445e-05, 4.78845486e-06, 3.02076402e-06, 1.60895066e-06,
       3.58983662e-06, 4.02548974e-06, 2.44222007e-06, 1.07755046e-05,
       2.39674947e-06, 3.63276934e-06, 3.29204916e-06, 3.42544846e-06,
       5.93545302e-06, 7.55549943e+03, 3.44229146e-06, 5.14429230e-06,
       3.19221782e-06, 1.33101126e-05, 4.89305992e-06, 5.92941150e-06,
       1.92498573e-05, 1.79728452e-06, 3.70614188e-06, 3.41418530e-06,
       1.00467857e-05, 3.56976667e-06, 4.61403234e-05, 2.75296860e-07,
       4.02921759e-06, 2.86526795e-06, 5.68835938e-06, 6.70138038e-06,
       2.70267009e-05, 3.46526207e-06, 2.21984774e-06, 2.60759388e-06,
       4.06286410e-06, 1.61886657e-06, 1.44808336e-06, 5.53543649e-06,
       1.02834198e-06, 3.32810745e-06, 1.51858216e-05, 2.37088836e-06,
       8.16043368e-07, 5.13129588e-06, 3.60078798e-06, 4.50528438e-06,
       5.20756796e-06, 1.22723143e-05, 3.12581932e-06, 4.16444829e-06,
      

In [125]:
%%time
mc_lt_pen.calibration(sampling_probabilities, calibration_matrix, calibration_target).x

CPU times: user 2.82 s, sys: 4.06 ms, total: 2.82 s
Wall time: 409 ms


array([ 1018.7949904 ,   338.35844878,   160.00629474,   161.03319896,
         425.61288589,   157.80723684,   373.26137728,   138.83191405,
         212.14050834,   196.06288646,   364.15400587,   200.76478558,
         405.7576084 ,   143.69820745,   210.26928743,   301.3289038 ,
         138.0961964 , 18913.27169843,   133.93433378,   147.85114548,
         130.26115985,  1771.49009669,   192.82841705,   152.59743591,
        1557.05656896,   765.66594436,   170.76719754,   139.4089952 ,
         460.06359786,   168.63211718,   328.21985306,  3867.31039226,
         149.47366841,   128.59834853,   208.51135901,   139.14654431,
         341.42746523,   146.24614851,   375.20294763,   218.45425073,
         165.34277423,   955.79921606,   911.54138272,  2087.36495761,
        5471.60267102,   248.25999089,  1837.26315849,   252.680389  ,
        1220.57543907,   497.1922944 ,   184.06022057,   222.03612175,
         152.96698266,  1686.11143517,   142.93572669,   184.49883891,
      