In [18]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [19]:
import numpy as np
import pandas as pd
import warnings
import sys

sys.path.append("../src")
from margin_calibration import MarginCalibration

In [20]:
warnings.simplefilter("ignore")

# Dataset Generation

In [21]:
# Create a 100 random observations with their respective
# sampling weights, such that those weights sum to 20 %
n_obs = 100
sampling_probabilities = np.random.rand(n_obs, 1).flatten()
sampling_probabilities = sampling_probabilities / sampling_probabilities.sum() *.2

# Create a matrix of size n_obs * n_margins, with margins ranging from 0 to 1000
n_margins = 2 # Let say we have two variables
calibration_matrix = 1000*np.random.rand(n_obs, n_margins)

# Now we create the calibration target
# It is of sier n_margins * 1 and contains the 
# sums of the margins over all the population
calibration_target = np.array([np.sum(calibration_matrix[:, i])*100 for i in range(calibration_matrix.shape[1])])

# The costs should be of size of the number of margins
costs = (1,1) # We give here same costs to both variables

# Let say we want to work with want to work with pandas dataframes 
# instead of numpy arrays
sampling_probabilities = pd.DataFrame(sampling_probabilities, columns=["weights"])
calibration_matrix = pd.DataFrame(calibration_matrix, columns = ["margin1", "margin2"])
calibration_target = pd.DataFrame(calibration_target, columns = ["margin_sums"])

# Margin Calibration

In [25]:
mc=MarginCalibration()
mc_logit=MarginCalibration("logit", .5, 1.5)
mc_rr=MarginCalibration("raking_ratio")
mc_lt=MarginCalibration("truncated_linear", .5, 1.5)

In [26]:
%%time
mc.calibration(sampling_probabilities, calibration_matrix, calibration_target).x

CPU times: user 1.47 s, sys: 3.97 ms, total: 1.48 s
Wall time: 215 ms


array([ 1.67086947e+01,  1.64024815e+02, -2.52622525e+01, -5.83901067e+01,
        3.89124251e+02,  2.44589520e+02,  1.37574082e+02,  8.30270041e+01,
       -4.83796542e+01,  1.45499583e+02,  2.03174374e+02,  4.50543955e+01,
       -2.20202656e+01,  3.89630268e+01,  1.67995810e+02, -1.47393635e+02,
        1.61091967e+02,  6.37571045e+01, -7.12642837e+01,  1.80073166e+02,
        1.83518092e+02,  6.19842575e+01,  4.91294508e+02, -1.53315769e+02,
        7.10325476e+02,  3.72439927e+02, -1.95718669e+02,  2.18944721e+02,
        1.36901960e+02,  1.43345609e+01,  4.71497303e+02,  2.22948429e+02,
       -1.25969393e+01,  3.25784495e+02,  1.45432322e+02,  1.55730172e+02,
        1.04292275e+02,  2.40935344e+02,  1.81854748e+03,  2.33246481e+03,
       -4.28008959e+01,  2.12917842e+02,  1.14965775e+02,  2.09195693e+02,
        7.59662237e+01, -6.93071999e+01,  6.14979989e+02, -1.48306780e+02,
        3.07016568e+01,  5.47246796e+01, -8.69409871e+02,  1.44535797e+02,
        1.43634251e+02,  

In [29]:
%%time
mc_logit.calibration(sampling_probabilities, calibration_matrix, calibration_target).x

CPU times: user 1h 36min 54s, sys: 3.46 s, total: 1h 36min 57s
Wall time: 3min 13s


array([ -78.41294159, -144.95361455, -228.79614472, -310.22276871,
        119.90326857,  545.3919883 ,  -73.43527041, -246.58539023,
       -470.2623863 ,  212.98329972,  173.07142676, -106.11540565,
       -189.08972791,    5.05267114,  182.02141769, -108.22405667,
        -28.15594657,   40.81716386, -446.01426363,  -75.34287919,
        195.48177191,  -16.12463089,  573.35457891, -380.26192839,
       2106.82727632,  299.05353633, -117.39075389,  -98.71755929,
        163.6476288 ,  -79.69411096,  491.35723332,  150.36807023,
       -228.73206454,  363.66137843,  136.00572882,  195.5194794 ,
        158.88725404,  186.40989429, 1339.53730603, 2749.85876493,
       -319.77251128,  161.79977996,   87.65398538,  147.21186354,
        -38.81703454, -397.28549639,  459.42858632, -615.64742316,
         -6.63472152,  -23.31231548, 1351.49489915, -162.16667468,
        -53.55793443,  310.88954072, 2024.06124614, -174.67657889,
        188.99290906,   56.36001649, -340.68502139,   94.38091

In [28]:
%%time
mc_rr.calibration(sampling_probabilities, calibration_matrix, calibration_target).x

CPU times: user 26min 52s, sys: 1 s, total: 26min 53s
Wall time: 53.7 s


array([  24.4951805 ,   79.77578921,   16.54788185,   11.99878859,
        169.43367318,  165.58846837,   83.81517443,   51.20931286,
         19.01016803,   61.94797518,   94.55025427,   23.09759966,
         15.79485794,   28.20166593,   78.17383747,   52.6377242 ,
         94.56404793,   85.88589182,    6.9281236 ,   91.07760018,
         79.2147622 ,   29.85096972,  210.50909389,   25.8748221 ,
        419.81324727,  188.39019745,   48.62752638,   97.95066986,
         59.92361719,   21.72418396,  215.6313801 ,  161.72492487,
         13.43485431,  169.54460736,   65.91387395,   72.09997686,
         48.49022025,  191.0153511 , 1118.18690816, 1090.59789604,
         34.53022919,  123.55002016,   53.0787076 ,  144.51207768,
         31.2758382 ,    8.01859522,  280.84109   ,    9.16163737,
         26.71233653,   28.14042104,   96.92780819,   74.7500818 ,
         87.77337017,  185.66333807,  422.10776191,   67.45499213,
        152.17546448,   80.55435141,   31.71125436,   59.37071

In [27]:
%%time
mc_lt.calibration(sampling_probabilities, calibration_matrix, calibration_target).x

CPU times: user 2h 26min 49s, sys: 10.1 s, total: 2h 26min 59s
Wall time: 4min 53s


array([-118.20195596,  -48.96124481, -181.5387671 , -234.79279261,
        142.33594201,  499.58378975,  -59.87617883, -117.51181204,
       -268.32578984,  -16.43324484,   77.36397711,  -69.34339597,
       -180.58086991,  -78.91499485,   82.93753152, -129.32330383,
        -25.41358188,   23.01998926, -300.00636028,  -50.91516871,
         85.3025247 ,  -26.14484463,  562.41215095, -376.65941942,
       2087.06931516,  267.63311249, -140.88722393,    5.63486758,
         47.43822593, -143.22299513,  482.93923022,  203.237706  ,
       -159.40057112,  338.83685531,   80.76987648,   58.29316499,
        -49.51951517,  225.83436535, 1553.13996938, 2743.50261913,
       -310.0944082 ,  170.51547315,   59.64206216,  186.06377311,
        -28.63537044, -238.96254273,  478.05548519, -394.27645646,
       -120.6317041 ,  -27.60200669, 1158.31597913, -116.01504578,
        -46.3500079 ,  260.7551634 , 2018.80764864, -150.73119686,
        210.66492543,  -42.94172851, -327.60489776,   33.39830

# Penalized Margin Calibration

In [ ]:
mc_pen=MarginCalibration(penalty=.1, costs=costs)
mc_logit_pen=MarginCalibration("logit", .5, 1.5, penalty=.1, costs=costs)
mc_rr_pen=MarginCalibration("raking_ratio", penalty=.1, costs=costs)
mc_lt_pen=MarginCalibration("truncated_linear", .5, 1.5, penalty=.1, costs=costs)

In [ ]:
%%time
mc_pen.calibration(sampling_probabilities, calibration_matrix, calibration_target).x

CPU times: user 2min 25s, sys: 170 ms, total: 2min 25s
Wall time: 1min 8s


array([ 8.74921073e+03,  2.35664135e+02,  7.53999287e+01,  3.29623027e+04,
       -4.32340219e+02, -1.02892193e+03, -9.09114259e+02, -1.73700063e+02,
        6.82001754e+02, -3.16844208e+02, -3.08586205e+03, -1.11812696e+03,
       -1.40310306e+03, -9.75123230e+02, -9.27518944e+02, -1.73472149e+02,
        2.34213809e+02, -9.63868221e+02, -1.16609860e+03,  2.19716554e+02,
        3.73281171e+02,  1.40162515e+02, -2.33421815e+02,  7.61804318e+02,
        5.16475245e+01, -3.62506694e+02, -1.42782672e+03, -1.81415169e+03,
        2.29878837e+01, -9.52666108e+02, -2.44145381e+02, -2.19417562e+03,
       -1.95458518e+03,  2.02399644e+02, -2.36414539e+02,  5.45398804e+02,
       -1.99159695e+03, -6.16484693e+01,  3.92046027e+02, -1.16722482e+02,
       -1.81819697e+03,  4.09757397e+02,  2.73863924e+02,  4.31430902e+03,
       -1.19837397e+03, -1.16854575e+03, -1.08147611e+03, -1.23596337e+03,
        1.99006028e+01, -3.90786992e+02, -6.82447176e+01, -1.04059340e+03,
       -2.56733755e+02, -

In [ ]:
%%time
mc_logit_pen.calibration(sampling_probabilities, calibration_matrix, calibration_target).x

CPU times: user 27.3 s, sys: 37.7 ms, total: 27.3 s
Wall time: 19.1 s


array([ 4730.13743753,   126.3159581 ,  1694.90014335, 30366.2316765 ,
         178.61299218,   225.00647065,   252.11591023,   198.66538876,
         328.52641718,   406.9842149 ,   943.25909324,   238.54110517,
         286.25653019,   286.46154002,   378.51799534,   173.96541391,
         141.09033139,   419.92746326,   742.38071838,   296.92077387,
         251.15104302,   296.93881718,   176.95264691,   297.55636233,
         438.5765216 ,   228.69316591,   314.09334209,   291.053651  ,
         340.67607427,   253.35699849,   194.40083657,   453.08769289,
         276.50999776,   210.19925402,   184.64539791,   256.70914464,
         334.03595586,   186.00159935,   144.55824709,   147.56897117,
         932.15020764,   150.1464805 ,   134.71524059,  1935.76202912,
         307.26093522,   299.15393329,   240.7412601 ,   379.3686566 ,
         157.80958771,   185.422735  ,   159.14549008,   507.03659444,
         479.59936621,   219.0241214 ,   159.28870286,   244.47344115,
      

In [ ]:
%%time
mc_rr_pen.calibration(sampling_probabilities, calibration_matrix, calibration_target).x

CPU times: user 4min 55s, sys: 196 ms, total: 4min 56s
Wall time: 2min 33s


array([ 6.43249228e+03,  4.06414647e+03, -8.02219790e+02,  1.96648781e+04,
       -1.18198960e+03, -5.12103302e+02,  1.14552327e+01,  4.52122393e+02,
        1.63367934e+03,  3.34518265e+03, -6.32726897e+02, -2.11262350e+03,
       -1.13171780e+03, -1.78065942e+03, -5.81045275e+02, -7.62337167e+02,
        1.76488226e+03, -5.39607894e+00,  1.43082293e+01, -4.46612279e+02,
        9.75739445e+00,  3.20289560e+01, -1.66622185e+02,  4.57258478e+02,
        1.76485755e+03,  1.90154765e+03, -1.98937633e+02, -2.76140609e+03,
       -1.20099617e+00,  1.70066079e+00,  1.60615652e+03, -5.60209300e+02,
       -1.79945599e+03,  5.24713271e+02, -1.00178019e+03,  5.61842324e+02,
       -1.20074002e+03,  2.72315075e+02, -2.46888450e+01,  6.01715865e+03,
       -3.26568849e+03, -1.33153035e+03, -9.59846100e+02,  3.50277308e+03,
       -6.02988966e+02,  1.82212136e+03, -1.42035104e+03, -4.20305554e+02,
        4.03572311e+01, -3.16668079e+00,  2.25281083e+03, -7.94640347e+01,
       -1.06624269e+03, -

In [ ]:
%%time
mc_lt_pen.calibration(sampling_probabilities, calibration_matrix, calibration_target).x

CPU times: user 10.7 s, sys: 18.9 ms, total: 10.7 s
Wall time: 5.2 s


array([ 4730.13743753,   126.3159581 ,  1694.90014335, 30366.2316765 ,
         178.61299218,   225.00647065,   252.11591023,   198.66538876,
         328.52641718,   406.9842149 ,   943.25909324,   238.54110517,
         286.25653019,   286.46154002,   378.51799534,   173.96541391,
         141.09033139,   419.92746326,   742.38071838,   296.92077387,
         251.15104302,   296.93881718,   176.95264691,   297.55636233,
         438.5765216 ,   228.69316591,   314.09334209,   291.053651  ,
         340.67607427,   253.35699849,   194.40083657,   453.08769289,
         276.50999776,   210.19925402,   184.64539791,   256.70914464,
         334.03595586,   186.00159935,   144.55824709,   147.56897117,
         932.15020764,   150.1464805 ,   134.71524059,  1935.76202912,
         307.26093522,   299.15393329,   240.7412601 ,   379.3686566 ,
         157.80958771,   185.422735  ,   159.14549008,   507.03659444,
         479.59936621,   219.0241214 ,   159.28870286,   244.47344115,
      